export const countryDialCodes = [
  { country: "United Kingdom", code: "+44" },
  { country: "United States", code: "+1" },
  { country: "Canada", code: "+1" },
  { country: "Australia", code: "+61" },
  { country: "Germany", code: "+49" },
  { country: "France", code: "+33" },
  { country: "Italy", code: "+39" },
  { country: "Spain", code: "+34" },
  { country: "Netherlands", code: "+31" },
  { country: "Belgium", code: "+32" },
  { country: "Sweden", code: "+46" },
  { country: "Norway", code: "+47" },
  { country: "Denmark", code: "+45" },
  { country: "Finland", code: "+358" },
  { country: "Ireland", code: "+353" },
  { country: "Austria", code: "+43" },
  { country: "Switzerland", code: "+41" },
  { country: "Portugal", code: "+351" },
  { country: "Czech Republic", code: "+420" },
  { country: "Hungary", code: "+36" },
  { country: "Slovakia", code: "+421" },
  { country: "Greece", code: "+30" },
  { country: "Croatia", code: "+385" },
  { country: "Slovenia", code: "+386" },
  { country: "Bulgaria", code: "+359" },
  { country: "Romania", code: "+40" },
  { country: "Estonia", code: "+372" },
  { country: "Latvia", code: "+371" },
  { country: "Lithuania", code: "+370" },
  { country: "Iceland", code: "+354" },
  { country: "Malta", code: "+356" },
];
